#!/usr/bin/env bash

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <apps-dir> <app> <args>"
    exit 1
fi

exec unshare -m -- bash -c '
set -e

APPS_SRC_DIR=$1
APPS_DEST_DIR=/usr/local/whack

mkdir -p "${APPS_DEST_DIR}"
mount --rbind "${APPS_SRC_DIR}" "${APPS_DEST_DIR}"
export PATH=${APPS_DEST_DIR}/bin:$PATH
exec "${@:2}"' "$0" "$@"
