#!/usr/bin/env python

import argparse

import whack.builder

def main():
    args = parse_args()
    builder_uris = ["git+https://github.com/mwilliamson/whack-builders.git"]
    builder = whack.builder.Builder(args.cache, builder_uris)
    builder.build_and_install(args.package, args.install_dir)
    
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('package')
    parser.add_argument('install_dir', metavar="install-dir")
    parser.add_argument("--cache", default=False, action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    main()
